name: Build Ruby for GitHub Actions
on:
  push:
jobs:
  build:
    runs-on: macos-arm-oss
    steps:
    - run: curl -O https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz
    - run: tar xf ruby-3.1.4.tar.gz
    - run: ./configure --enable-shared --prefix=$HOME/tmp-ruby-3.1.4
      working-directory: ruby-3.1.4
    - run: make
      working-directory: ruby-3.1.4
    - run: make install
      working-directory: ruby-3.1.4
